In [1]:
import pandas as pd

In [2]:
df_before = pd.read_csv("/Users/bern/Documents/GitHub/fyp-chatbot/tests/test_results/1702_step1.csv")
df_before

,conversation_id,message_order,query,chatbot_response,context,cost,tokens
0,65f172e8192f78bab2a94539,1,is there lab next week?,There will be no lab sessions next week as it ...,I have posted Exercise 4 (linear Regression) f...,0.000240,1502
1,65f172e8192f78bab2a94539,2,what week is it now,"Currently, it is Week 6 of the course, which s...",You MAY also mention how you are planning to s...,0.000223,1421
2,65f172e8192f78bab2a94539,3,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,0.000254,1485
3,65f172e8192f78bab2a94539,4,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,0.000266,1565
4,65f17301192f78bab2a9453c,1,what type of questions will I get in the AI th...,The AI Theory Quiz will include various types ...,Please do not panic if anything goes wrong. Yo...,0.000237,1366
...,...,...,...,...,...,...,...
554,6613bd2c0104d14eacfb5691,2,i'm struggling with learning the coding part t...,The coding part of the course can be challengi...,"Only once the project groups are formed, you c...",0.000405,1947
555,6613bd460104d14eacfb5693,1,How does greedy search work?,"Sorry, I am unable to answer your question. I ...",README does not need to have all minor details...,0.000194,1284
556,6613bd460104d14eacfb5693,2,give me an example of greedy search,"Sorry, I am unable to answer your question. I ...","Cheers,\n\nOng Chin Ann\n\nExercise 8 : Agent ...",0.000272,1804
557,6613c1da0104d14eacfb5695,1,Can you explain to me the differences between ...,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...,0.000366,1675
558,6613c1da0104d14eacfb5695,2,can you give me an example of each type of agent,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...,0.000348,1772

In [3]:
df_after = pd.read_csv("/Users/bern/Documents/GitHub/fyp-chatbot/tests/test_results/1702_step3_50ans_first200q.csv")
df_after

,conversation_id,message_order,query,chatbot_response,context,cost,tokens
0,65f172e8192f78bab2a94539,1,is there lab next week?,"Sorry, I am unable to answer your question. I ...",I have posted Exercise 4 (linear Regression) f...,0.000228,1510
1,65f172e8192f78bab2a94539,2,what week is it now,"Today is February 17, 2025. Based on the cours...","Best Regards & Have a great weekend ahead,\n\n...",0.000244,1524
2,65f172e8192f78bab2a94539,3,what is the deadline for my assignment,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...,0.000220,1416
3,65f172e8192f78bab2a94539,4,what is the deadline for my assignment,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...,0.000224,1443
4,65f17301192f78bab2a9453c,1,what type of questions will I get in the AI th...,The AI Theory Quiz will consist of around 20-2...,Please do not panic if anything goes wrong. Yo...,0.000428,1685
...,...,...,...,...,...,...,...
554,6613bd2c0104d14eacfb5691,2,i'm struggling with learning the coding part t...,"The coding part can be challenging at first, b...",Question: Is there a quiz available in the LAM...,0.000367,1814
555,6613bd460104d14eacfb5693,1,How does greedy search work?,Greedy search works by making a series of choi...,Question: What is the difference between futur...,0.000239,1319
556,6613bd460104d14eacfb5693,2,give me an example of greedy search,"Sorry, I am unable to answer your question. I ...",Question: What is the difference between futur...,0.000213,1410
557,6613c1da0104d14eacfb5695,1,Can you explain to me the differences between ...,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...,0.000364,1622
558,6613c1da0104d14eacfb5695,2,can you give me an example of each type of agent,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...,0.000340,1769

In [4]:
merged_df = pd.merge(df_before, df_after, on=['conversation_id','message_order', 'query'], how='inner', suffixes=('_before', '_after'))
merged_df

,conversation_id,message_order,query,chatbot_response_before,context_before,cost_before,tokens_before,chatbot_response_after,context_after,cost_after,tokens_after
0,65f172e8192f78bab2a94539,1,is there lab next week?,There will be no lab sessions next week as it ...,I have posted Exercise 4 (linear Regression) f...,0.000240,1502,"Sorry, I am unable to answer your question. I ...",I have posted Exercise 4 (linear Regression) f...,0.000228,1510
1,65f172e8192f78bab2a94539,2,what week is it now,"Currently, it is Week 6 of the course, which s...",You MAY also mention how you are planning to s...,0.000223,1421,"Today is February 17, 2025. Based on the cours...","Best Regards & Have a great weekend ahead,\n\n...",0.000244,1524
2,65f172e8192f78bab2a94539,3,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,0.000254,1485,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...,0.000220,1416
3,65f172e8192f78bab2a94539,4,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,0.000266,1565,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...,0.000224,1443
4,65f17301192f78bab2a9453c,1,what type of questions will I get in the AI th...,The AI Theory Quiz will include various types ...,Please do not panic if anything goes wrong. Yo...,0.000237,1366,The AI Theory Quiz will consist of around 20-2...,Please do not panic if anything goes wrong. Yo...,0.000428,1685
...,...,...,...,...,...,...,...,...,...,...,...
554,6613bd2c0104d14eacfb5691,2,i'm struggling with learning the coding part t...,The coding part of the course can be challengi...,"Only once the project groups are formed, you c...",0.000405,1947,"The coding part can be challenging at first, b...",Question: Is there a quiz available in the LAM...,0.000367,1814
555,6613bd460104d14eacfb5693,1,How does greedy search work?,"Sorry, I am unable to answer your question. I ...",README does not need to have all minor details...,0.000194,1284,Greedy search works by making a series of choi...,Question: What is the difference between futur...,0.000239,1319
556,6613bd460104d14eacfb5693,2,give me an example of greedy search,"Sorry, I am unable to answer your question. I ...","Cheers,\n\nOng Chin Ann\n\nExercise 8 : Agent ...",0.000272,1804,"Sorry, I am unable to answer your question. I ...",Question: What is the difference between futur...,0.000213,1410
557,6613c1da0104d14eacfb5695,1,Can you explain to me the differences between ...,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...,0.000366,1675,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...,0.000364,1622
558,6613c1da0104d14eacfb5695,2,can you give me an example of each type of agent,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...,0.000348,1772,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...,0.000340,1769

In [5]:
# remove unused columns
merged_df = merged_df.drop(columns=['cost_before', 'cost_after', 'tokens_before', 'tokens_after'])
merged_df

,conversation_id,message_order,query,chatbot_response_before,context_before,chatbot_response_after,context_after
0,65f172e8192f78bab2a94539,1,is there lab next week?,There will be no lab sessions next week as it ...,I have posted Exercise 4 (linear Regression) f...,"Sorry, I am unable to answer your question. I ...",I have posted Exercise 4 (linear Regression) f...
1,65f172e8192f78bab2a94539,2,what week is it now,"Currently, it is Week 6 of the course, which s...",You MAY also mention how you are planning to s...,"Today is February 17, 2025. Based on the cours...","Best Regards & Have a great weekend ahead,\n\n..."
2,65f172e8192f78bab2a94539,3,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...
3,65f172e8192f78bab2a94539,4,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...
4,65f17301192f78bab2a9453c,1,what type of questions will I get in the AI th...,The AI Theory Quiz will include various types ...,Please do not panic if anything goes wrong. Yo...,The AI Theory Quiz will consist of around 20-2...,Please do not panic if anything goes wrong. Yo...
...,...,...,...,...,...,...,...
554,6613bd2c0104d14eacfb5691,2,i'm struggling with learning the coding part t...,The coding part of the course can be challengi...,"Only once the project groups are formed, you c...","The coding part can be challenging at first, b...",Question: Is there a quiz available in the LAM...
555,6613bd460104d14eacfb5693,1,How does greedy search work?,"Sorry, I am unable to answer your question. I ...",README does not need to have all minor details...,Greedy search works by making a series of choi...,Question: What is the difference between futur...
556,6613bd460104d14eacfb5693,2,give me an example of greedy search,"Sorry, I am unable to answer your question. I ...","Cheers,\n\nOng Chin Ann\n\nExercise 8 : Agent ...","Sorry, I am unable to answer your question. I ...",Question: What is the difference between futur...
557,6613c1da0104d14eacfb5695,1,Can you explain to me the differences between ...,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...
558,6613c1da0104d14eacfb5695,2,can you give me an example of each type of agent,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...

In [6]:
filtered_df = merged_df[merged_df['chatbot_response_before'] != merged_df['chatbot_response_after']]
filtered_df

,conversation_id,message_order,query,chatbot_response_before,context_before,chatbot_response_after,context_after
0,65f172e8192f78bab2a94539,1,is there lab next week?,There will be no lab sessions next week as it ...,I have posted Exercise 4 (linear Regression) f...,"Sorry, I am unable to answer your question. I ...",I have posted Exercise 4 (linear Regression) f...
1,65f172e8192f78bab2a94539,2,what week is it now,"Currently, it is Week 6 of the course, which s...",You MAY also mention how you are planning to s...,"Today is February 17, 2025. Based on the cours...","Best Regards & Have a great weekend ahead,\n\n..."
2,65f172e8192f78bab2a94539,3,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...
3,65f172e8192f78bab2a94539,4,what is the deadline for my assignment,The deadline for your assignment (Lab Exercise...,The grading will be done by your Lab TA. It is...,The deadline for all AI LAMs is 1st May 2359.,Question: What is the definition of a cost fun...
4,65f17301192f78bab2a9453c,1,what type of questions will I get in the AI th...,The AI Theory Quiz will include various types ...,Please do not panic if anything goes wrong. Yo...,The AI Theory Quiz will consist of around 20-2...,Please do not panic if anything goes wrong. Yo...
...,...,...,...,...,...,...,...
553,6613bd2c0104d14eacfb5691,1,"hi, are the lab exercises enough to improve my...",The lab exercises are designed to provide hand...,You MAY also mention how you are planning to s...,The lab exercises are designed to complement t...,Question: Can you explain unsupervised learnin...
554,6613bd2c0104d14eacfb5691,2,i'm struggling with learning the coding part t...,The coding part of the course can be challengi...,"Only once the project groups are formed, you c...","The coding part can be challenging at first, b...",Question: Is there a quiz available in the LAM...
555,6613bd460104d14eacfb5693,1,How does greedy search work?,"Sorry, I am unable to answer your question. I ...",README does not need to have all minor details...,Greedy search works by making a series of choi...,Question: What is the difference between futur...
557,6613c1da0104d14eacfb5695,1,Can you explain to me the differences between ...,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...,"Rational agents, utility-based agents, and goa...",Exercise 7 : Problem & Environment Formulation...
558,6613c1da0104d14eacfb5695,2,can you give me an example of each type of agent,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...,Sure! Here are examples of each type of agent ...,Exercise 7 : Problem & Environment Formulation...

In [7]:
# export to xlsx
filtered_df.to_excel("/Users/bern/Documents/GitHub/fyp-chatbot/tests/test_results/1702_step1_step3_50ans_first200q.xlsx", index=False)

/Users/bern/anaconda3/envs/fyp_chatbot_venv/lib/python3.13/site-packages/xlsxwriter/worksheet.py:1251: UserWarning: Ignoring URL 'https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWU2ZGEwOWMtN2YzNy00MWIzLWIyYTctYzdhN2RmNDhmZWUx%40thread.v2/0?context=%7b%22Tid%22%3a%2215ce9348-be2a-462b-8fc0-e1765a9b204a%22%2c%22Oid%22%3a%22ef9b4326-833b-40d9-a480-00094ee5149c%22%7d

P/S: For subsequent Review Lecture in Week 10 & 11, we will be using the same link.

See you all later, the more the merrier.



Best Regards,

Ong Chin Ann
Lecturer (SC1015/CE1115/CZ1115)
email: chinann.ong@ntu.edu.sg

DS quiz score released

Posted on: Thursday, March 21, 2024 10:00:44 AM SGT

Dear Students,

I have released the marks for DS Theory Quiz. The statistics are as follows.

Count : 984  |  Total marks : 30  |  Mean : 18.93  |  Median : 19.25  |  StdDev : 4.33  |  Max : 29.5  |  Min : 3.5 |  Q1 : 16.25  |  Q3 : 22

If you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.

Regards,
Smitha

Lab Exercise 8 Released (5%)

Posted on: Wednesday, April 3, 2024 9:06:35 AM SGT

Dear Students,

---------------
Revised/enhance your solution after the discussion and then submit before the deadline.

Resume your mini-project while waiting for Lab Exercise 8 to be released (Week 11).

Last but not least, do join the 50-mins live virtual session as we will discuss a key items for Module 3 - Search.
If time premitted, we can discuss a bit on Lab Exercise 7 too.

The link to join the session as follow ( Please join using your NTU Email account only, so that you will not stucked in the Lobby ):

https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWU2ZGEwOWMtN2YzNy00MWIzLWIyYTctYzdhN2RmNDhmZWUx%40thread.v2/0?context=%7b%22Tid%22%3a%2215ce9348-be2a-462b-8fc0-e1765a9b204a%22%2c%22Oid%22%3a%22ef9b4326-833b-40d9-a480-00094ee5149c%22%7d

P/S: For subsequent Review Lecture in Week 10 & 11, we will be using the same link.

See you all later, the more the merrier.



Best Regards,

Ong Chin Ann
Lecturer (SC1015/CE1115/CZ1115)
email: chinann.ong@ntu.edu.sg

DS quiz score released

---------------
Week: 0
Date: 07-Jan-24
Activity: W1 : LAMS Released (DS)

---------------
Dear Students,

I have released the marks for DS Theory Quiz. The statistics are as follows.

Count : 984  |  Total marks : 30  |  Mean : 18.93  |  Median : 19.25  |  StdDev : 4.33  |  Max : 29.5  |  Min : 3.5 |  Q1 : 16.25  |  Q3 : 22

If you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.

Regards,
Smitha

Lab Exercise 8 Released (5%)

Posted on: Wednesday, April 3, 2024 9:06:35 AM SGT

Dear Students,

Good Day & Good Morning!!!

Just to post & inform you that the requirements for Lab Exercise 8 (Graded) is now released and available under the "Lab Session" menu.

Do note that based on the course calendar, the Lab Session for this week (Week 11) is intended for Mini-Project consultation, hence, you are advise to make use of the lab session this week to work on your mini-project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 8.

---------------
You may choose to present as a complete team too, with everyone talking about individual portions on which they contributed (please manage the time effectively in such cases).

You DO NOT need to show your faces in the presentation, but you may of course show faces, if you want. Please speak yourselves in the video; DO NOT use a robo-voiceover.

The presentation is primarily through PPT/PDF/Google Slides, plus some portion of your Jupyter Notebooks and workflow to describe parts of the project, as and when required.

You DO NOT need to show raw code during the presentation. You may show pieces of your code, if you think that is important. Otherwise, mainly show results and observations.

If you are planning to go back-and-forth between your slides and the notebooks (to show code or visualizations), manage your time carefully and make sure you touch all points.' with link or location/anchor > 2079 characters since it exceeds Excel's limit for URLS
  warn(
/Users/bern/anaconda3/envs/fyp_chatbot_venv/lib/python3.13/site-packages/xlsxwriter/worksheet.py:1251: UserWarning: Ignoring URL 'https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWU2ZGEwOWMtN2YzNy00MWIzLWIyYTctYzdhN2RmNDhmZWUx%40thread.v2/0?context=%7b%22Tid%22%3a%2215ce9348-be2a-462b-8fc0-e1765a9b204a%22%2c%22Oid%22%3a%22ef9b4326-833b-40d9-a480-00094ee5149c%22%7d

P/S: For subsequent Review Lecture in Week 10 & 11, we will be using the same link.

See you all later, the more the merrier.



Best Regards,

Ong Chin Ann
Lecturer (SC1015/CE1115/CZ1115)
email: chinann.ong@ntu.edu.sg

DS quiz score released

Posted on: Thursday, March 21, 2024 10:00:44 AM SGT

Dear Students,

I have released the marks for DS Theory Quiz. The statistics are as follows.

Count : 984  |  Total marks : 30  |  Mean : 18.93  |  Median : 19.25  |  StdDev : 4.33  |  Max : 29.5  |  Min : 3.5 |  Q1 : 16.25  |  Q3 : 22

If you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.

Regards,
Smitha

Lab Exercise 8 Released (5%)

Posted on: Wednesday, April 3, 2024 9:06:35 AM SGT

Dear Students,

---------------
Dear Students,

I have released the marks for DS Theory Quiz. The statistics are as follows.

Count : 984  |  Total marks : 30  |  Mean : 18.93  |  Median : 19.25  |  StdDev : 4.33  |  Max : 29.5  |  Min : 3.5 |  Q1 : 16.25  |  Q3 : 22

If you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.

Regards,
Smitha

Lab Exercise 8 Released (5%)

Posted on: Wednesday, April 3, 2024 9:06:35 AM SGT

Dear Students,

Good Day & Good Morning!!!

Just to post & inform you that the requirements for Lab Exercise 8 (Graded) is now released and available under the "Lab Session" menu.

Do note that based on the course calendar, the Lab Session for this week (Week 11) is intended for Mini-Project consultation, hence, you are advise to make use of the lab session this week to work on your mini-project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 8.

---------------
Please do not panic if anything goes wrong. You will be considered for a make-up if there is a genuine technical issue that can't be solved by your TA or the Lab In-Charge during the quiz. Please check the sample questions attached herewith carefully to get a feel for the tests. Note that your tests are NOT going to be exactly the same -- variations are of course expected within and between the quiz slots.

Artificial Intelligence : Theory Quiz

Artificial Intelligence Theory Quiz will take place in Week 14 -- on Monday, 22 April.
Venue/Time : Check the attached xlsx file to find the allocation for your Lab Group.

This quiz is based on the entire AI theory covered in the LAMS Sequences (Module 1-Module 4) and review lectures for AI.
Please read the following instructions carefully before attempting the Quiz, and follow the instructions given by you at the lab.

Venue and Time

---------------
I wish you will enjoy the exercise and learn more through it, rather than just attempt it for the marks. As always, I will post the solution after the week 5 and after all submissions end (in case there are extensions).

Please note that LABS on Feb 9th is cancelled and will be done on Feb 16th. Affected lab groups please note.

Regards,
Smitha

DS Theory quiz details , Exercise 4 posted

Posted on: Thursday, February 15, 2024 2:07:10 PM SGT

Data Science Theory Quiz details have been posted under "Quizzes" section on NTULearn course site. The quiz will be held across 2 slots on 8 March, Friday: 12:30 pm - 2:00 pm and 2:30 pm - 4:00 pm. Please check the quiz slot and venue allocation carefully in that information, and come to the designated lab on time. For part time students, the session will be on 8 March, Friday, 7:00 pm - 8:30 pm @HPL.

---------------
Make-Up quiz in Week 8.

Note that you will need to have a valid reason with supporting document.

Further details of Make up quiz will be communicated to you separately.

Do note that the Make up quiz will be more challenging than the original one as it is done in week 8 and

               you have more time for preparation.

For students who are writting make up quiz, the quiz is on wednesday 13th march at Hardware projects lab from 4.30 to 5.30pm.

Please do not panic if anything goes wrong. You will be considered for a make-up if there is a genuine technical issue that can't be solved by your TA or the Lab In-Charge during the quiz. Please check the sample questions attached herewith carefully to get a feel for the tests. Note that your tests are NOT going to be exactly the same -- variations are of course expected within and between the quiz slots.

Artificial Intelligence : Theory Quiz' with link or location/anchor > 2079 characters since it exceeds Excel's limit for URLS
  warn(
/Users/bern/anaconda3/envs/fyp_chatbot_venv/lib/python3.13/site-packages/xlsxwriter/worksheet.py:1251: UserWarning: Ignoring URL 'https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWU2ZGEwOWMtN2YzNy00MWIzLWIyYTctYzdhN2RmNDhmZWUx%40thread.v2/0?context=%7b%22Tid%22%3a%2215ce9348-be2a-462b-8fc0-e1765a9b204a%22%2c%22Oid%22%3a%22ef9b4326-833b-40d9-a480-00094ee5149c%22%7d

P/S: For subsequent Review Lecture in Week 10 & 11, we will be using the same link.

See you all later, the more the merrier.



Best Regards,

Ong Chin Ann
Lecturer (SC1015/CE1115/CZ1115)
email: chinann.ong@ntu.edu.sg

DS quiz score released

Posted on: Thursday, March 21, 2024 10:00:44 AM SGT

Dear Students,

I have released the marks for DS Theory Quiz. The statistics are as follows.

Count : 984  |  Total marks : 30  |  Mean : 18.93  |  Median : 19.25  |  StdDev : 4.33  |  Max : 29.5  |  Min : 3.5 |  Q1 : 16.25  |  Q3 : 22

If you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.

Regards,
Smitha

Lab Exercise 8 Released (5%)

Posted on: Wednesday, April 3, 2024 9:06:35 AM SGT

Dear Students,

---------------
Question: When will the results of the DS Quiz be released?
Answer: The results of the DS Quiz will be released on 13th March.

Question: What are the steps to join the development team for Ask Narelle?
Answer: You may email professor_x@ntu.sg if you wish to join the AskNarelle team.

Question: What is the average grade for the SC1015 Introduction to Data Science and Artificial Intelligence course?
Answer: This course is graded on a bellcurve, thus the average grade is B+. Your final grade depends on how well you do relative to your peers in the course.

Question: What is the date of the final quiz?
Answer: The date of the final quiz is on 14th April.

Question: What are some tips for studying SC1015?
Answer: To study this module well, start with mini project and the basics of programming, statistics, and math, work on real-world projects, use online resources, practice regularly, and stay updated with industry trends. Be consistent with your lectures and keep track of your labs well.

---------------
Please do not panic if anything goes wrong. You will be considered for a make-up if there is a genuine technical issue that can't be solved by your TA or the Lab In-Charge during the quiz. Please check the sample questions attached herewith carefully to get a feel for the tests. Note that your tests are NOT going to be exactly the same -- variations are of course expected within and between the quiz slots.

Artificial Intelligence : Theory Quiz

Artificial Intelligence Theory Quiz will take place in Week 14 -- on Monday, 22 April.
Venue/Time : Check the attached xlsx file to find the allocation for your Lab Group.

This quiz is based on the entire AI theory covered in the LAMS Sequences (Module 1-Module 4) and review lectures for AI.
Please read the following instructions carefully before attempting the Quiz, and follow the instructions given by you at the lab.

Venue and Time

---------------
Dear Students,

I have released the marks for DS Theory Quiz. The statistics are as follows.

Count : 984  |  Total marks : 30  |  Mean : 18.93  |  Median : 19.25  |  StdDev : 4.33  |  Max : 29.5  |  Min : 3.5 |  Q1 : 16.25  |  Q3 : 22

If you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.

Regards,
Smitha

Lab Exercise 8 Released (5%)

Posted on: Wednesday, April 3, 2024 9:06:35 AM SGT

Dear Students,

Good Day & Good Morning!!!

Just to post & inform you that the requirements for Lab Exercise 8 (Graded) is now released and available under the "Lab Session" menu.

Do note that based on the course calendar, the Lab Session for this week (Week 11) is intended for Mini-Project consultation, hence, you are advise to make use of the lab session this week to work on your mini-project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 8.

---------------
Question: What is the date of the final quiz?
Answer: The date of the final quiz is on 14th April.

Question: What are some tips for studying SC1015?
Answer: To study this module well, start with mini project and the basics of programming, statistics, and math, work on real-world projects, use online resources, practice regularly, and stay updated with industry trends. Be consistent with your lectures and keep track of your labs well.

Question: Is there a quiz available in the LAMS?
Answer: No, the LAMs are purely part of the lecture content and will not overlap with the quiz questions

Question: What LLM API are you using?
Answer: Ask Narelle uses Microsoft Azure's OpenAI models. This particular model is gpt-4o.

Question: Who is the teaching assistant for the FCS4 lab?
Answer: Mr. Y' with link or location/anchor > 2079 characters since it exceeds Excel's limit for URLS
  warn(